# Generated by Django 2.2.6 on 2019-11-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191114_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
    ]
