# Generated by Django 2.2.5 on 2019-11-14 14:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191114_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to=blog.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
