# Generated by Django 2.2.6 on 2019-11-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_text',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
    ]
