# Generated by Django 2.2.8 on 2019-12-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_body_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, db_index=True, help_text='Изображение добавлять например: текст {*.jpg(Расширение может быть любым)} текс'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.CharField(db_index=True, default='', help_text='Название изображение записывать с расширением', max_length=150),
        ),
    ]
